# Generated by Django 4.1.3 on 2022-12-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_menu'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.menu'),
        ),
    ]
