# Generated by Django 4.1.3 on 2022-11-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='home.menu'),
        ),
    ]
